language: c
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get -qq update
 - sudo apt-get -qq build-dep python
 - sudo apt-get -qq install clang gcc
# there's no `make distcheck` target
script: autoreconf --force --install --verbose && ./configure && make -j24 && make -j24 test && sudo make install
